version: '3.8'

services:
  db:
    image: myawesomeapps/postgres-with-cron:15
    container_name: vibes_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 98732145
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:v10.1.1
    container_name: vibes_postgrest
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/postgres
      PGRST_DB_SCHEMAS: api
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'

  web:
    image: node:18-alpine
    container_name: vibes_web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    depends_on:
      db:
        condition: service_healthy

networks:
  default:
    name: vibes_network
